version: '3'

services:
  account-service:
    environment:
      BANK_CLIENT_ID: b4bdf874-8c03-5bd8-8fd7-5e409dfd82c0
      DB_USER: onboardingbankuser
      DB_NAME: customer_service_db
      DB_PASSWORD: 5LQHPSB1JUe215Ew
      JWT_SECRET_KEY: j0DvBiM41Swn5yaDxVhfknVcLxBKsC+osrAnVZ2N6g9x+cEQhixLHubvcN4dP854IarxNdcLk2vz1qWsgWkliZzvFC19DnGWGcNFJftDM5MMObzHpA2NETQWFz0G+Q8BUZkBivpy9GetCl4/KmOs/YULYLUHxlhQBD8ikb6AdqQ=
    build: .
    ports:
      - "9001:8080"
    networks:
      - onboardingbank
networks:
  onboardingbank:
    external: true